PrimeSoho/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from core import views
from PrimeSoho import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('j/', include('juridico.urls')),
    path('imoveis/', include('imoveis.urls')),
    path('c/', include('clientes.urls')),
]

#if settings.DEBUG:
    #from debug_toolbar
    #urlpatterns = [
        #path('__debug__/', include(debug_toolbar.urls)),
    #] + urlpatterns

handler404 = views.error_404
handler500 = views.error_500

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),  # Página inicial
    path('login/', views.login_view, name='login_view'),  # Página de login
    path('home/', views.home, name='home'),  # Página de home
    path("recuperar_senha/", views.recover_password_view, name="recuperar_senha"),  # URL para recuperar senha 
    path("recuperar_senha/<str:token>/", views.recover_password_view, name="recuperar_senha_token"),  # URL para recuperar senha com token
]

juridico/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
import os

app_name = 'juridico'

urlpatterns = [
    path('formulario/', views.listar_formularios, name='form_hub'),
    path('formulario/<str:folder>/', views.formulario, name='formulario'),
    path('home/', views.j_home, name='home'),
]

# Adiciona uma URL específica para a pasta output
current_dir = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(current_dir, 'output')
urlpatterns += static('/output/', document_root=output_path)

core/models.py
from django.db import models
from PrimeSoho.models import core

class Token_Recuperar_Senha(core):
    usuario = models.CharField('Usuario', max_length=255, editable=False)
    token = models.CharField('Token', max_length=255, editable=False)
    data_utilizacao = models.DateTimeField('Data de utilização', null=True, blank=True)

    def __str__(self):
        return self.usuario

    class Meta:
        verbose_name = 'Token de recuperação de senha'
        verbose_name_plural = 'Tokens de recuperação de senha'
        ordering = ['usuario']

core/forms.py
from django import forms

core/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
#get_object_or_404
from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login 
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.utils.crypto import get_random_string
from django.urls import reverse
from django.contrib.auth.hashers import make_password
from django.http import Http404
from .models import Token_Recuperar_Senha
from django.utils import timezone

# Simular armazenamento de tokens (melhor usar um modelo no banco)
password_reset_tokens = {}

# View para a página inicial
def index(request):
    return render(request, 'index.html')

# View para o login
def login_view(request):
    # Caso o usuário já esteja autenticado, redireciona para a página inicial
    if request.user.is_authenticated:
        return redirect('core:home')

    if request.method == 'POST':
        # Obtém os dados do formulário
        usuario = request.POST.get('username')
        senha = request.POST.get('password')

        # Autentica o usuário com as credenciais fornecidas
        user = authenticate(request, username=usuario, password=senha)

        if user is not None:
            # Se o usuário for válido, realiza o login
            login(request, user)

            # Retorna uma resposta JSON indicando sucesso
            return JsonResponse({'success': True, 'message': 'Login realizado com sucesso!'})
        else:
            # Se as credenciais forem inválidas, retorna uma resposta JSON de erro
            return JsonResponse({'success': False, 'message': 'Usuário ou senha inválidos!'})

    # Se for uma requisição GET, apenas renderiza o formulário de login
    return render(request, 'login.html')


def recover_password_view(request, token=None):
    try:
        if request.method == 'POST':
            if token:  
                # 🌟 2️⃣ Se há um token, processa a redefinição de senha 🌟
                try:
                    new_password = request.POST.get('new_password')
                    if not new_password:
                        raise ValueError("Senha vazia recebida!")

                    if token not in password_reset_tokens:
                        raise KeyError("Token inválido ou expirado!")

                    username = Token_Recuperar_Senha.objects.filter(token=token, ativo=True).first().usuario
                    user = User.objects.get(username=username)
                    user.password = make_password(new_password)  # Criptografa a senha nova
                    user.save()
                    Token_Recuperar_Senha.objects.filter(token=token, ativo=True).update(ativo=False, data_utilizacao=timezone.now())
                    send_mail(
                        'Senha Redefinida',
                        'Sua senha foi redefinida com sucesso. Se você não fez isso, entre em contato conosco por: <a href="mailto:vg.bitello@gmail.com">vg.bitello@gmail.com</a>.',
                        settings.DEFAULT_FROM_EMAIL,  
                        [user.email],
                        fail_silently=False,
                    )
                    
                    return JsonResponse({'success': True, 'message': 'Senha redefinida com sucesso!'})

                except KeyError as e:
                    print(f"[ERROR] Erro de token: {str(e)}")
                    return JsonResponse({'success': False, 'message': 'Token inválido ou expirado.'})
                except User.DoesNotExist:
                    print(f"[ERROR] Usuário não encontrado para token: {token}")
                    return JsonResponse({'success': False, 'message': 'Usuário não encontrado.'})
                except Exception as e:
                    print(f"[ERROR] Erro inesperado ao redefinir senha: {str(e)}")
                    return JsonResponse({'success': False, 'message': f'Erro interno: {str(e)}'})

            else:  
                # 🌟 1️⃣ Se não há token, processa o pedido de recuperação 🌟
                try:
                    username = request.POST.get('username')
                    if not username:
                        raise ValueError("Campo de usuário vazio!")

                    user = User.objects.get(username=username)

                    # Gerar e armazenar o token
                    token = get_random_string(length=32)
                    password_reset_tokens[token] = username  # Salvar o token temporariamente

                    # Criar link real de recuperação
                    reset_link = request.build_absolute_uri(reverse('core:recuperar_senha_token', kwargs={'token': token}))

                    # Enviar email com link para resetar senha
                    send_mail(
                        'Recuperação de Senha',
                        f'Clique no link para redefinir sua senha: {reset_link}',
                        settings.DEFAULT_FROM_EMAIL,  
                        [user.email],
                        fail_silently=False,
                    )

                    DataDB = Token_Recuperar_Senha(usuario=username, token=token)
                    DataDB.save()

                except Exception as e:
                    return JsonResponse({'success': False, 'message': f'Erro interno: {str(e)}'})

                return JsonResponse({'success': True, 'message': 'Se o usuário existir, um e-mail foi enviado com instruções para recuperar a senha.'})

        # 🌟 3️⃣ Renderizar página diferente dependendo se há um token 🌟
        if token and Token_Recuperar_Senha.objects.filter(token=token, ativo=True).exists():
            return render(request, 'recuperar_senha.html', {'token': token})
        else:
            raise Http404("Token inválido ou não encontrado.")

    except Exception as e:
        print(f"[CRITICAL] Erro fatal: {str(e)}")


# View para a página de home
@login_required(login_url='/login/')
def home(request):
    return render(request, 'home.html')


def error_404(request, exception):
    tempalte = loader.get_template('errors/404.html')
    return HttpResponse(content=tempalte.render(), content_type='text/html; charset=utf-8', status=404)


def error_500(request):
    tempalte = loader.get_template('errors/500.html')
    return HttpResponse(content=tempalte.render(), content_type='text/html; charset=utf-8', status=500)

core/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CORE</title>
    <link rel="icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style_colors.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_index.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="/usuario"><div id="icon-corretor"><svg id="img-user"><use xlink:href="{% static 'svg/user.svg' %}#user"></use></svg></div></a></li>
                <li><a href="{% url 'juridico:home' %}">Juridico</a></li>
                <li><a href=""></a></li>
            </ul>
        </nav>
    </header>

    <main>
        
    </main>

    <footer>
        <p>©2025 Sistema de Automação. Todos os direitos reservados.</p>
        <p>Contato: <a href="mailto:vg.bitello@gmail.com">vg.bitello@gmail.com</a></p>
    </footer>
</body>
</html>

core/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CORE</title>
    <link rel="icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style_colors.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_index.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="/usuario"><div id="icon-corretor"><svg id="img-user"><use xlink:href="{% static 'svg/user.svg' %}#user"></use></svg></div></a></li>
                <li><a href="#">Imoveis</a></li>
                <li><a href="/login">Login</a></li>
            </ul>
        </nav>
    </header>

    <main>

        <section class="start">
            <div class="start-left">
                <h1>Core</h1>
                <img src="{% static 'img/01-Logo-Prime-Principal.png.webp' %}" alt="Equipe Bia souza 2025">
            </div>
            <div class="start-right">
                <p>Um painel desenvolvido para a facilitação de trabalho dos associados da <span class="highlight">Prime Soho</span></p>
            </div>
        </section>

        <div id="line"></div>

        <section class="imoveis">
            <h2>Imoveis</h2>
            <ul>
                <li><a href="#" class="imoveis-list"><div><img class="imovel-img" src="{% static 'img/imv/imv1.jpeg' %}"></div><p class="imovel-valor">4.800.000R$</p></a></li>
                <li><a href="#" class="imoveis-list"><div><img class="imovel-img" src="{% static 'img/imv/imv2.jpeg' %}"></div><p class="imovel-valor">4.800.000R$</p></a></li>
                <li><a href="#" class="imoveis-list"><div><img class="imovel-img" src="{% static 'img/imv/imv3.jpeg' %}"></div><p class="imovel-valor">4.800.000R$</p></a></li>
                <li><a href="#" class="imoveis-list"><div><img class="imovel-img" src="{% static 'img/imv/imv1.jpeg' %}"></div><p class="imovel-valor">4.800.000R$</p></a></li>
                <li><a href="#" class="imoveis-list"><div><img class="imovel-img" src="{% static 'img/imv/imv2.jpeg' %}"></div><p class="imovel-valor">4.800.000R$</p></a></li>
                <li><a href="#" class="imoveis-list"><div><img class="imovel-img" src="{% static 'img/imv/imv3.jpeg' %}"></div><p class="imovel-valor">4.800.000R$</p></a></li>
                <li><a href="#" class="imoveis-list"><div><img class="imovel-img" src="{% static 'img/imv/imv1.jpeg' %}"></div><p class="imovel-valor">4.800.000R$</p></a></li>
                <li><a href="#" class="imoveis-list"><div><img class="imovel-img" src="{% static 'img/imv/imv2.jpeg' %}"></div><p class="imovel-valor">4.800.000R$</p></a></li>
                <li><a href="#" class="imoveis-list"><div><img class="imovel-img" src="{% static 'img/imv/imv3.jpeg' %}"></div><p class="imovel-valor">4.800.000R$</p></a></li>
            </ul>
        </section>

    </main>

    <footer>
        <p>©2025 Sistema de Automação. Todos os direitos reservados.</p>
        <p>Contato: <a href="mailto:vg.bitello@gmail.com">vg.bitello@gmail.com</a></p>
    </footer>
</body>
</html>

core/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CORE-Login</title>
    <link rel="icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style_colors.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
    <link rel="stylesheet" href="{% static 'css/popup.css' %}">
    <script src="{% static 'js/api.js' %}"></script>

    <meta name="csrf-token" content="{{ csrf_token }}">
</head>
<body>

    <main class="main-content">

        <section class="login-box">
            <a class="back-button" href="../"><svg class="logo-svg"><use xlink:href="{% static 'svg/circle-cross.svg' %}#circle-cross"></use></svg></a>
            <div class="form-container">
                <svg class="user-svg"><use xlink:href="{% static 'svg/user.svg' %}#user"></svg>
                <form class="login-form" action="{% url 'core:login_view' %}" method="post" novalidate id="loginForm">
                    <label for="username" class="form-label">Usuario</label>
                    <input type="text" name="username" id="username" class="form-input" required>
                    <label for="password" class="form-label">Senha</label>
                    <input type="password" name="password" id="password" class="form-input" required>
                    <div class="form-options">
                        <div class="remember-me">
                            <input type="checkbox" name="remember" id="remember" class="form-checkbox">
                            <label for="remember" class="form-label">Lembrar-me</label>
                        </div>
                        <a href="" class="forgot-password" id="forgotPasswordLink">Esqueceu a senha?</a>
                    </div>
                    <input type="submit" value="Entrar" class="form-submit">
                </form>
            </div>
        </section>
        
    </main>

    <!-- Estrutura do popup já existente -->
    <div class="popup-overlay" id="popupOverlay" style="display: none;"></div>
    <div class="popup" id="popup" style="display: none;">
        <button class="close-btn" id="closePopup">×</button>
        <div id="popup-message"></div>
        <div class="input-container">
            <label for="username-input">Nome de usuário:</label>
            <input type="text" id="username-input" placeholder="Seu nome de usuário..." class="input-field">
            <button class="submit-btn">Enviar</button>
        </div>
    </div>


    <footer class="footer">
        <p class="footer-copyright">©2025 Sistema de Automação. Todos os direitos reservados.</p>
        <p class="footer-contact">Contato: <a href="mailto:vg.bitello@gmail.com" class="footer-email">vg.bitello@gmail.com</a></p>
    </footer>

    <script src="{% static 'js/js-login.js' %}"></script>
    <script src="{% static 'js/popup.js' %}"></script>
</body>
</html>

core/templates/recuperar_senha.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CORE - Redefinir Senha</title>
    <link rel="icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style_colors.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
    <link rel="stylesheet" href="{% static 'css/popup.css' %}">
    <script src="{% static 'js/api.js' %}"></script>

    <meta name="csrf-token" content="{{ csrf_token }}">
</head>
<body>

    <main class="main-content">

        <section class="login-box">
            <a class="back-button" href="../">
                <svg class="logo-svg"><use xlink:href="{% static 'svg/circle-cross.svg' %}#circle-cross"></use></svg>
            </a>
            <div class="form-container">
                <svg class="user-svg"><use xlink:href="{% static 'svg/user.svg' %}#user"></use></svg>
                <h2 class="form-title">Redefinir Senha</h2>
                <p class="form-subtext">Digite sua nova senha e a confirme para completar a redefinição.</p>

                <form class="login-form" id="passwordResetConfirmForm">
                    <label for="new_password" class="form-label">Nova Senha</label>
                    <input type="password" name="new_password" id="new_password" class="form-input" required>

                    <label for="confirm_password" class="form-label">Confirmar Senha</label>
                    <input type="password" name="confirm_password" id="confirm_password" class="form-input" required>

                    <input type="submit" value="Redefinir Senha" class="form-submit">
                </form>

                <p id="responseMessage" class="form-message hidden"></p>
            </div>
        </section>
        
    </main>

    <footer class="footer">
        <p class="footer-copyright">©2025 Sistema de Automação. Todos os direitos reservados.</p>
        <p class="footer-contact">Contato: <a href="mailto:vg.bitello@gmail.com" class="footer-email">vg.bitello@gmail.com</a></p>
    </footer>

    <script src="{% static 'js/js-recuperar.js' %}"></script>

</body>
</html>