PrimeSoho/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500
from core import views
from PrimeSoho import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('j/', include('juridico.urls')),
    path('imoveis/', include('imoveis.urls')),
    path('c/', include('clientes.urls')),
]

#if settings.DEBUG:
    #from debug_toolbar
    #urlpatterns = [
        #path('__debug__/', include(debug_toolbar.urls)),
    #] + urlpatterns

handler404 = views.error_404
handler500 = views.error_500

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),  # Página inicial
    path('login/', views.login_view, name='login_view'),  # Página de login
    path('home/', views.home, name='home'),  # Página de home
    path("recuperar_senha/", views.recover_password_view, name="recuperar_senha"),  # URL para recuperar senha 
    path("recuperar_senha/<str:token>/", views.recover_password_view, name="recuperar_senha_token"),  # URL para recuperar senha com token
]

juridico/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
import os

app_name = 'juridico'

urlpatterns = [
    path('formulario/', views.listar_formularios, name='form_hub'),
    path('formulario/<str:folder>/', views.formulario, name='formulario'),
    path('home/', views.j_home, name='home'),
]

# Adiciona uma URL específica para a pasta output
current_dir = os.path.dirname(os.path.abspath(__file__))
output_path = os.path.join(current_dir, 'output')
urlpatterns += static('/output/', document_root=output_path)

juridico/models.py
from django.db import models

# Create your models here.

juridico/forms.py
from django import forms
from django.forms import formset_factory
import json
from django.utils import timezone

class DynamicForm(forms.Form):
    datalist_html = ""

    def __init__(self, parsed_data, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.datalist_html = ""  # Reset datalist_html for each instance
        
        # Para campos independentes (sem grupo)
        for nome, campo in parsed_data.items():
            if not campo.get('form', False) or campo.get('grupo', ''):
                continue  # Ignora campos sem a chave 'form' ou com grupo

            # Criar campo normal
            field = self.create_field(nome, campo)
            if field:
                self.fields[nome] = field

    def create_field(self, nome, campo):
        """
        Cria um campo do formulário com base nas informações fornecidas.
        """
        if not campo.get('form', False):
            return None
            
        descricao = campo['descricao']
        tipo = campo['tipo']
        requerido = campo['requerido']
        condicoes = campo.get('condicao', {})
        grupo = campo.get('grupo', '')
        block = campo.get('block', '')

        # Converte as condições para JSON (se existirem)
        condicao_attr = json.dumps(condicoes, ensure_ascii=False) if condicoes else ''

        # Atributos do widget para o campo
        widget_attrs = {
            'id': nome,
            'class': 'form-control',
            'placeholder': '',
            'list': '',
            'data-condicao': condicao_attr,
            'data-grupo': grupo,
            'data-block': block,  # Add block attribute
        }

        # Criação do campo de acordo com o tipo
        field = None
        
        if tipo == 'string':
            field = forms.CharField(label=descricao, required=requerido, widget=forms.TextInput(attrs=widget_attrs))
        elif tipo == 'number':
            widget_attrs['placeholder'] += '0'
            widget_attrs['class'] += ' number'
            field = forms.CharField(label=descricao, required=requerido, widget=forms.TextInput(attrs=widget_attrs))
        elif tipo == 'email':
            widget_attrs['placeholder'] += 'example@domain.com'
            widget_attrs['class'] += ' email'
            field = forms.EmailField(label=descricao, required=requerido, widget=forms.EmailInput(attrs=widget_attrs))
        elif tipo == 'date':
            curent_date = timezone.localdate()
            widget_attrs['type'] = 'date'
            widget_attrs['value'] = curent_date
            field = forms.DateField(label=descricao, required=requerido, widget=forms.DateInput(attrs=widget_attrs))
        elif tipo == 'phone':
            widget_attrs['placeholder'] += '+55 (00) 90000-0000'
            widget_attrs['class'] += ' phone'
            field = forms.CharField(label=descricao, required=requerido, widget=forms.TextInput(attrs=widget_attrs))
        elif tipo == 'cpf':
            widget_attrs['placeholder'] += '000.000.000-00'
            widget_attrs['class'] += ' cpf'
            field = forms.CharField(label=descricao, required=requerido, widget=forms.TextInput(attrs=widget_attrs))
        elif tipo == 'select' and 'variaveis' in campo:
            choices = [(var, var) for var in campo['variaveis']]
            field = forms.ChoiceField(label=descricao, required=requerido, choices=choices, widget=forms.Select(attrs=widget_attrs))
        elif tipo == 'textarea':
            field = forms.CharField(label=descricao, required=requerido, widget=forms.Textarea(attrs=widget_attrs))
        elif tipo == 'checkbox':
            field = forms.BooleanField(label=descricao, required=requerido, widget=forms.CheckboxInput(attrs=widget_attrs))
        elif tipo == 'datalist' and 'variaveis' in campo:
            widget_attrs['list'] += f'opcoes_{nome}'
            field = forms.CharField(label=descricao, required=requerido, widget=forms.TextInput(attrs=widget_attrs))
            
            # Acumular o HTML do datalist
            datalist_html = f'<datalist id="opcoes_{nome}">'
            for opcao in campo['variaveis']:
                datalist_html += f'<option value="{opcao}">'
            datalist_html += '</datalist>'
            self.datalist_html += datalist_html

        return field

    def get_datalist_html(self):
        """Retorna o HTML completo dos datalists gerados."""
        return self.datalist_html


def create_group_form_class(campos_grupo):
    """
    Cria uma classe de formulário dinâmica para um grupo específico de campos.
    """
    class GroupForm(forms.Form):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            # Obtém o prefixo do formulário, que inclui o número da cópia
            form_prefix = self.prefix
            
            # Atualiza os widgets com o prefixo correto
            for field_name, field in self.fields.items():
                if hasattr(field.widget, 'attrs'):
                    # Atualiza o ID do widget com o prefixo completo
                    field.widget.attrs['id'] = f"{form_prefix}-{field_name}" if form_prefix else field_name
                    
                    # Atualiza as condições se existirem
                    if 'data-condicao' in field.widget.attrs and field.widget.attrs['data-condicao']:
                        condicoes = json.loads(field.widget.attrs['data-condicao'])
                        condicoes_ajustadas = {}
                        
                        # Cria o novo prefixo para as condições (mantendo apenas o número do formulário)
                        if form_prefix and '-' in form_prefix:
                            numero_form = form_prefix.split('-')[-1]
                            novo_prefixo = f"form-{numero_form}-"
                            
                            for campo, valor in condicoes.items():
                                # Remove qualquer prefixo anterior (caso exista)
                                if '-' in campo:
                                    campo_base = campo.split('-')[-1]
                                else:
                                    campo_base = campo
                                    
                                campo_ajustado = f"{novo_prefixo}{campo_base}"
                                condicoes_ajustadas[campo_ajustado] = valor
                            
                            # Atualiza o atributo com as condições ajustadas
                            field.widget.attrs['data-condicao'] = json.dumps(condicoes_ajustadas, ensure_ascii=False)
    
    # Adiciona campos ao formulário do grupo
    dynamic_form_instance = DynamicForm({})  # Criar uma instância vazia de DynamicForm
    for nome, campo_info in campos_grupo.items():
        if not campo_info.get('form', False):
            continue
            
        # Criar o campo sem gerar datalists duplicados
        field = dynamic_form_instance.create_field(nome, campo_info)
        if field:
            GroupForm.base_fields[nome] = field
    
    return GroupForm


def get_form_and_formsets(parsed_data, request_data=None, request_files=None):
    """
    Função auxiliar para criar formulário principal e formsets.
    Retorna o formulário principal, os formsets, e todos os datalists HTML combinados.
    """
    # Separar campos independentes dos campos agrupados
    independent_fields = {nome: campo for nome, campo in parsed_data.items() 
                            if not campo.get('grupo')}
    
    # Obter todos os grupos únicos presentes nos campos
    grupos_unicos = set(campo.get('grupo') for nome, campo in parsed_data.items() 
                        if campo.get('grupo'))
    
    # Organizar campos por grupo
    grouped_fields = {}
    for grupo in grupos_unicos:
        grouped_fields[grupo] = {nome: campo for nome, campo in parsed_data.items() 
                                if campo.get('grupo') == grupo}
    
    # Inicializar o formulário principal
    independent_form = None
    
    if request_data:
        independent_form = DynamicForm(independent_fields, request_data, request_files)
    else:
        independent_form = DynamicForm(independent_fields)
    
    # Inicializar formsets
    formsets = {}
    
    # Coletar todos os datalists
    all_datalists_html = ""
    
    # Adicionar datalists do formulário principal
    all_datalists_html += independent_form.get_datalist_html()
    
    # Criar e adicionar datalists para todos os campos de grupo
    for grupo, campos_grupo in grouped_fields.items():
        # Criar o FormSet específico para este grupo
        GroupFormSet = formset_factory(
            create_group_form_class(campos_grupo),
            extra=1
        )
        
        # Instanciar o formset com ou sem dados do POST
        if request_data:
            formsets[grupo] = GroupFormSet(
                request_data,
            )
        else:
            formsets[grupo] = GroupFormSet()
        
        # Coletar datalists dos campos do grupo
        # Fazemos isso aqui para garantir que os datalists sejam criados apenas uma vez por tipo de campo
        for nome, campo in campos_grupo.items():
            if campo.get('tipo') == 'datalist' and 'variaveis' in campo:
                datalist_html = f'<datalist id="opcoes_{nome}">'
                for opcao in campo['variaveis']:
                    datalist_html += f'<option value="{opcao}">'
                datalist_html += '</datalist>'
                all_datalists_html += datalist_html
    
    # Retornar o formulário principal, os formsets e todos os datalists HTML
    return independent_form, formsets, all_datalists_html

def validate_forms(independent_form, formsets):
    """
    Valida o formulário principal e todos os formsets.
    Se um campo obrigatório não for enviado, ele é ignorado.
    Se for enviado em branco, a validação falha.

    Args:
        independent_form: O formulário principal

juridico/views.py
import os
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .utils.yaml_receiver import load_yaml, parse_yaml, multiplicador_yaml_options, options_yaml_options
from .utils.docx_generator import generate_docx
from django.contrib.auth.decorators import login_required
from .forms import DynamicForm, get_form_and_formsets, validate_forms
from .utils.db_input import save_form_data

# Obtém o diretório onde o arquivo views.py está localizado
current_dir = os.path.dirname(os.path.abspath(__file__))

@login_required(login_url='/login/')
def j_home(request):
    return render(request, 'j_home.html')

@login_required(login_url='/login/')
def listar_formularios(request):

    # Lista de formulários disponíveis
    formularios = []
    
    # Percorre as pastas dentro de 'docs' para encontrar os arquivos YAML
    for folder in os.listdir(os.path.join(current_dir, 'docs')):
        folder_path = os.path.join(os.path.join(current_dir, 'docs'), folder)
        if os.path.isdir(folder_path):
            yaml_file = os.path.join(folder_path, f'{folder}.yaml')
            if os.path.exists(yaml_file):
                formularios.append(folder)
    
    # Renderiza a página com a lista de formulários
    return render(request, 'form_hub.html', {'formularios': formularios})

#@login_required(login_url='/login/')
def formulario(request, folder):
    # Caminho da pasta onde os YAMLs estão localizados
    yaml_file_path = os.path.join(current_dir, 'docs', folder, f'{folder}.yaml')
    
    if not os.path.exists(yaml_file_path):
        return JsonResponse({"error": "Arquivo YAML não encontrado."}, status=404)
        
    yaml_data = load_yaml(yaml_file_path)
    
    if not yaml_data:
        return JsonResponse({"error": "Erro ao carregar o arquivo YAML."}, status=500)
        
    parsed_data = parse_yaml(yaml_data)
    multiplicador_data_options = multiplicador_yaml_options(yaml_data)
    
    if request.method == 'POST':
        # Usar a função auxiliar para criar formulário e formsets
        independent_form, formsets, all_datalists = get_form_and_formsets(parsed_data, request.POST, request.FILES)
        
        # Validar formulário e formsets
        is_valid, dados_combinados, errors = validate_forms(independent_form, formsets)

        config_yaml = options_yaml_options(yaml_data)
        
        if not is_valid:
            print (errors)
            return JsonResponse({
                'error': 'Por favor, preencha todos os campos obrigatórios corretamente.',
                'errors': errors
            }, status=400)
            
        try:
            # Gerar o arquivo DOCX
            try:
                docx_name = generate_docx(dados_combinados, folder, yaml_data, multiplicador_data_options)
                print (docx_name)
                if config_yaml.get('db', False):
                    save_form_data(dados_combinados, config_yaml)
            except Exception as e:
                return JsonResponse({
                    'error': f'Erro ao gerar o arquivo DOCX: {str(e)}'
                }, status=500)

            if os.path.exists(os.path.join(current_dir, 'output', docx_name)):
                file_url = os.path.join('/j/output/', docx_name)
                return JsonResponse({
                    'message': 'O arquivo DOCX foi gerado com sucesso!',
                    'file_url': file_url
                })
            else:
                return JsonResponse({"error": "Erro ao gerar o arquivo DOCX."}, status=500)
        except Exception as e:
            return JsonResponse({
                'error': f'Erro durante o processamento do formulário: {str(e)}'
            }, status=500)
    else:
        # Requisição GET - criar formulário e formsets vazios
        independent_form, formsets, all_datalists = get_form_and_formsets(parsed_data)

    return render(request, 'form.html', {
        'independent_form': independent_form,
        'formsets': formsets,
        'all_datalists': all_datalists  
    })

juridico/templates/form.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário Dinâmico</title>
    <link rel="icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style_colors.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_form.css' %}">
    <link rel="stylesheet" href="{% static 'css/popup.css' %}">
    <script src="{% static 'js/api.js' %}"></script>
    <script src="{% static 'js/RegEx.js' %}"></script>

    <meta name="csrf-token" content="{{ csrf_token }}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="/usuario"><div id="icon-corretor"><svg id="img-user"><use xlink:href="{% static 'svg/user.svg' %}#user"></use></svg></div></a></li>
                <li><a href="{% url 'juridico:home' %}">juridico</a></li>
                <li><a href="{% url 'juridico:form_hub' %}">Docx</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section class="Formulario">
            <form method="POST" id="dynamicForm" action="{{ request.path }}">
                
                <!-- Campos independentes -->
                <div class="independent-fields">
                    {% for field in independent_form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.errors %}
                                <div class="error">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    
                    {{ independent_form.datalist_html|safe }}
                </div>
                
                <!-- Campos agrupados (formsets) -->
                {% for grupo, formset in formsets.items %}
                    <div class="grupo-campos" data-grupo="{{ grupo }}">
                        <h3>{{ grupo }}</h3>
                        {{ formset.management_form }}

                        <div class="formset-controls flex" data-grupo="{{ grupo }}">
                            <label for="{{ grupo }}-quantidade">Quantidade de {{ grupo }}:</label>
                            <input type="number" id="{{ grupo }}-quantidade" class="form-control multiplicador" 
                                    value="1" min="1" max="100" data-grupo="{{ grupo }}">
                            <button type="button" class="btn btn-secondary multiplicador-btn" 
                                    data-grupo="{{ grupo }}">Confirmar</button>
                        </div>

                        <div class="formset" data-grupo="{{ grupo }}">
                            {% for form in formset %}
                                <div class="formset-form">

                                    {% for field in form.visible_fields %}
                                        <div class="form-group">
                                            {{ field.label_tag }}
                                            {{ field }}
                                            {% if field.errors %}
                                                <div class="error">
                                                    {% for error in field.errors %}
                                                        {{ error }}
                                                    {% endfor %}
                                                </div>
                                            {% endif %}
                                            {% if field.help_text %}
                                                <small class="form-text text-muted">{{ field.help_text }}</small>
                                            {% endif %}
                                        </div>
                                    {% endfor %}

                                    {% for hidden_field in form.hidden_fields %}
                                        {{ hidden_field }}
                                    {% endfor %}

                                    {% if form.datalist_html %}
                                        {{ form.datalist_html|safe }}
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}

                <button type="submit" id="enviar" class="btn btn-primary">Enviar</button>
            </form>
            {{ all_datalists|safe }}
        </section>
    </main>

    <!-- Popup HTML -->
    <div class="popup-overlay" id="popupOverlay" style="display: none;"></div>
    <div class="popup" id="popup" style="display: none;">
        <button class="close-btn" id="closePopup">×</button>
        <div id="popup-message"></div>
        <div class="input-container">
            <label for="username-input">Nome de usuário:</label>
            <input type="text" id="username-input" placeholder="Seu nome de usuário..." class="input-field">
            <button class="submit-btn">Enviar</button>
        </div>
    </div>

    <script src="{% static 'js/script_form.js' %}"></script>
    <script src="{% static 'js/popup.js' %}"></script>
</body>
</html>

juridico/templates/form_hub.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CORE-Lista de Formulários</title>
    <link rel="icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style_colors.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_forms_hub.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="/usuario"><div id="icon-corretor"><svg id="img-user"><use xlink:href="{% static 'svg/user.svg' %}#user"></use></svg></div></a></li>
                <li><a href="{% url 'core:home' %}">Home</a></li>
                <li><a href="{% url 'juridico:home' %}">Juridico</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section class="S1">
            <h1>Lista de DOCX disponiveis</h1>
            <ul>
                {% for formulario in formularios %}
                    <li><a href="{% url 'juridico:formulario' formulario %}">{{ formulario }}</a></li>
                {% endfor %}
            </ul>
        </section>
    </main>

    <footer>
        <p>©2025 Sistema de Automação. Todos os direitos reservados.</p>
        <p>Contato: <a href="mailto:vg.bitello@gmail.com">vg.bitello@gmail.com</a></p>
    </footer>
</body>
</html>

<!-- Adicionar Js para comportar erros ao abrir docx -->

juridico/templates/j_home.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CORE</title>
    <link rel="icon" href="{% static 'icon/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style_colors.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/style_j_home.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="/usuario"><div id="icon-corretor"><svg id="img-user"><use xlink:href="{% static 'svg/user.svg' %}#user"></use></svg></div></a></li>
                <li><a href="{% url 'core:home' %}">Home</a></li>
                <li><a href=""></a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section class="S1">
            <div class="div_btns">
                <a href="{% url 'juridico:form_hub' %}"><button class="btn">Criar DOCX</button></a>
            </div>
        </section>
    </main>

    <footer>
        <p>©2025 Sistema de Automação. Todos os direitos reservados.</p>
        <p>Contato: <a href="mailto:vg.bitello@gmail.com">vg.bitello@gmail.com</a></p>
    </footer>
</body>
</html>